# Generated by Django 4.0 on 2022-04-24 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наме городища')),
                ('slug', models.CharField(blank=True, max_length=50, verbose_name='Slug он и ест slug')),
            ],
            options={
                'verbose_name': 'Наме городища',
                'verbose_name_plural': 'Наме городища',
            },
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=85, verbose_name='Заголовок метрики')),
                ('subname', models.CharField(blank=True, max_length=83, verbose_name='подзаголовок')),
                ('file_name', models.CharField(blank=True, max_length=50, verbose_name='Файл данных')),
                ('variable', models.CharField(blank=True, max_length=50, verbose_name='Переменная данных')),
                ('ID_out', models.CharField(blank=True, max_length=50, verbose_name='ID_div для вывода')),
                ('tagsmet', models.CharField(blank=True, max_length=83, verbose_name='Переключатели вида - набор - через ,')),
                ('slider', models.IntegerField(blank=True, null=True, verbose_name='Слайдер вкл/выкл')),
                ('barline', models.CharField(blank=True, max_length=10, verbose_name='тип Bar - bar, Line - scatter')),
                ('laycolor', models.CharField(blank=True, max_length=12, verbose_name='Цвет фона графика')),
                ('barmode', models.CharField(blank=True, max_length=10, verbose_name='Тип Bar - пусто  overlay  stack')),
                ('rangestart', models.CharField(blank=True, max_length=10, verbose_name='Дата начала в формате строки 2021-05-01')),
            ],
            options={
                'verbose_name': 'Метрики',
                'verbose_name_plural': 'Метрики базовые',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event_images/')),
                ('title', models.CharField(max_length=300, verbose_name='Наме поста')),
                ('date', models.DateTimeField()),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Наме статейки',
                'verbose_name_plural': 'Наме стат',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_page', models.IntegerField(blank=True, null=True, verbose_name='Страница - номер')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='сортировка')),
                ('column', models.IntegerField(blank=True, null=True, verbose_name='колонка на странице (если одна - null')),
                ('name_page', models.CharField(blank=True, max_length=50, null=True, verbose_name='Заголовок метрики')),
                ('metric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mettrd.graph', verbose_name='Метрика')),
            ],
            options={
                'verbose_name': 'Метрики на страницы',
                'verbose_name_plural': 'Вывод метрик на страницу',
            },
        ),
    ]
