# Generated by Django 4.0 on 2022-04-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mettrd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='metric',
        ),
        migrations.AddField(
            model_name='page',
            name='metric',
            field=models.IntegerField(blank=True, null=True, verbose_name='Метрика'),
        ),
    ]
