# Generated by Django 4.0 on 2022-01-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mettrd', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Наме городища', 'verbose_name_plural': 'Наме городища'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Наме статейки', 'verbose_name_plural': 'Наме стат'},
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Наме городища'),
        ),
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.CharField(blank=True, max_length=50, verbose_name='Slug он и ест slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Наме поста'),
        ),
    ]
