# Generated by Django 4.0 on 2022-02-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mettrd', '0002_alter_city_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Метрика')),
                ('file_name', models.CharField(max_length=50, verbose_name='Файл данных')),
                ('variable', models.CharField(max_length=50, verbose_name='Переменная данных')),
                ('ID_out', models.CharField(max_length=50, verbose_name='ID_div для вывода')),
            ],
            options={
                'verbose_name': 'Метрика',
                'verbose_name_plural': 'Метрика',
            },
        ),
    ]
