# Generated by Django 4.0 on 2022-02-12 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mettrd', '0003_graph'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graph',
            options={'verbose_name': 'Метрики', 'verbose_name_plural': 'Метрики базовые'},
        ),
    ]
