# Generated by Django 4.0 on 2022-04-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mettrd', '0005_graph_subname_graph_tagsmet_alter_graph_id_out_and_more'),
    ]
    operations = [
        migrations.AddField(
            model_name='graph',
            name='barmode',
            field=models.CharField(blank=True, max_length=10, verbose_name='Тип Bar - пусто  overlay  stack'),
        ),
        migrations.AddField(
            model_name='graph',
            name='laycolor',
            field=models.CharField(blank=True, max_length=12, verbose_name='Цвет фона графика'),
        ),
        migrations.AddField(
            model_name='graph',
            name='rangestart',
            field=models.CharField(blank=True, max_length=10, verbose_name='Дата начала в формате строки 2021-05-01'),
        ),
        migrations.AddField(
            model_name='graph',
            name='slider',
            field=models.IntegerField(blank=True, null=True, verbose_name='Слайдер вкл/выкл'),
        ),
        migrations.AlterField(
            model_name='graph',
            name='tagsmet',
            field=models.CharField(blank=True, max_length=83, verbose_name='Переключатели вида - набор - через ,'),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_page', models.IntegerField(blank=True, null=True, verbose_name='Страница - номер')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='сортировка')),
                ('column', models.IntegerField(blank=True, null=True, verbose_name='колонка на странице (если одна - null')),
                ('name_page', models.CharField(blank=True, max_length=50, null=True, verbose_name='Заголовок метрики')),
                ('metric', models.ManyToManyField(to='mettrd.Graph', verbose_name='Номер метрики')),
            ],
            options={
                'verbose_name': 'Метрики на страницы',
                'verbose_name_plural': 'Вывод метрик на страницу',
            },
        ),
    ]
