# Generated by Django 4.0 on 2022-04-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mettrd', '0006_graph_barline_graph_barmode_graph_laycolor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph',
            name='id',
        ),
        migrations.AddField(
            model_name='graph',
            name='id',
            field=models.ManyToManyField(to='mettrd.Page'),
        ),
        migrations.AlterField(
            model_name='page',
            name='metric',
            field=models.ManyToManyField(to='mettrd.Graph'),
        ),
    ]
