# Generated by Django 4.0 on 2022-06-28 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mettrd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursorapi', models.CharField(max_length=35, verbose_name='Курсор запроса')),
                ('resultapi', models.CharField(max_length=12, null=True, verbose_name='результат')),
                ('timeapi', models.DateTimeField(blank=True, verbose_name='Время запроса')),
                ('countapi', models.IntegerField(blank=True, null=True, verbose_name='кол-во полученных записей')),
            ],
            options={
                'verbose_name': 'Курсор с Алерт',
                'verbose_name_plural': 'Курсор с Алерт',
            },
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=85, verbose_name='Заголовок метрики')),
                ('subname', models.CharField(blank=True, max_length=83, verbose_name='подзаголовок')),
                ('file_name', models.CharField(blank=True, max_length=50, verbose_name='Файл данных')),
                ('variable', models.CharField(blank=True, max_length=50, verbose_name='Переменная данных')),
                ('ID_out', models.CharField(blank=True, max_length=50, verbose_name='ID_div для вывода')),
                ('tagsmet', models.CharField(blank=True, max_length=83, verbose_name='Переключатели вида - набор - через ,')),
                ('slider', models.IntegerField(blank=True, null=True, verbose_name='Слайдер вкл/выкл')),
                ('barline', models.CharField(blank=True, max_length=10, verbose_name='тип Bar - bar, Line - scatter')),
                ('laycolor', models.CharField(blank=True, max_length=12, verbose_name='Цвет фона графика')),
                ('barmode', models.CharField(blank=True, max_length=10, verbose_name='Тип Bar - пусто  overlay  stack')),
                ('rangestart', models.CharField(blank=True, max_length=10, verbose_name='Дата начала в формате строки 2021-05-01')),
            ],
            options={
                'verbose_name': 'Метрики',
                'verbose_name_plural': 'Метрики базовые',
            },
        ),
        migrations.CreateModel(
            name='Tranzact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, null=True, verbose_name='Монета')),
                ('id_trz', models.IntegerField(null=True, verbose_name='ID alert')),
                ('time_trz', models.IntegerField(null=True, verbose_name='Время')),
                ('amount', models.FloatField(null=True, verbose_name='Кол-во')),
                ('amount_usd', models.FloatField(null=True, verbose_name='Кол-во')),
                ('blockchain', models.CharField(max_length=20, null=True, verbose_name='blockchain')),
                ('transaction_type', models.CharField(max_length=20, null=True, verbose_name='transaction_type')),
                ('from_owner_type', models.CharField(max_length=20, null=True, verbose_name='From тип')),
                ('to_owner_type', models.CharField(max_length=20, null=True, verbose_name='To тип')),
                ('from_owner', models.CharField(max_length=20, null=True, verbose_name='From биржа')),
                ('to_owner', models.CharField(max_length=20, null=True, verbose_name='To биржа')),
                ('from_address', models.CharField(max_length=100, null=True, verbose_name='From адрес')),
                ('to_address', models.CharField(max_length=100, null=True, verbose_name='To адрес')),
                ('hash', models.CharField(max_length=100, null=True, verbose_name='hash')),
                ('transaction_count', models.IntegerField(null=True, verbose_name='transaction_count')),
                ('date_trz', models.DateTimeField(blank=True, verbose_name='Время транз')),
            ],
            options={
                'verbose_name': 'Транзакции с Алерта',
                'verbose_name_plural': 'Транзакции с Алерта',
            },
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Наме городища', 'verbose_name_plural': 'Наме городища'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Наме статейки', 'verbose_name_plural': 'Наме стат'},
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Наме городища'),
        ),
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.CharField(blank=True, max_length=50, verbose_name='Slug он и ест slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Наме поста'),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_page', models.IntegerField(blank=True, null=True, verbose_name='Страница - номер')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='сортировка')),
                ('column', models.IntegerField(blank=True, null=True, verbose_name='колонка на странице (если одна - null')),
                ('name_page', models.CharField(blank=True, max_length=50, null=True, verbose_name='Заголовок метрики')),
                ('coment', models.CharField(blank=True, max_length=300, null=True, verbose_name='Коментарий к графику')),
                ('metric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mettrd.graph', verbose_name='Метрика')),
            ],
            options={
                'verbose_name': 'Метрики на страницы',
                'verbose_name_plural': 'Вывод метрик на страницу',
            },
        ),
    ]
